package Mentoring;

import io.github.bonigarcia.wdm.WebDriverManager;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;

public class Practice2 {
    public static void main(String[] args) throws InterruptedException {
        WebDriverManager.chromedriver().setup();
        WebDriver driver = new ChromeDriver();
        driver.get("https://automationexercise.com/");
        WebElement page = driver.findElement(By.xpath("//html"));
        System.out.println(page.isDisplayed() ? "HomePage is visible Successfully" : "HomePage is Not Visible");
        WebElement signIn = driver.findElement(By.xpath("//i[@class='fa fa-lock']"));
        signIn.click();
        WebElement newUser = driver.findElement(By.xpath("//h2[contains(text(),'New')]"));
        System.out.println(newUser.isDisplayed() ? "New User SignUp is Visible" : "New User SignUp is NOT Visible");
        WebElement name = driver.findElement(By.xpath("//input[@name='name']"));
        name.sendKeys("Guli");
        WebElement email = driver.findElement(By.xpath("//input[@data-qa='signup-email']"));
        email.sendKeys("Guli22@gmail.com");
        WebElement signUpButton = driver.findElement(By.xpath("//button[@data-qa='signup-button']"));
        signUpButton.click();
        Thread.sleep(3000);
        WebElement enterAccountInfo = driver.findElement(By.xpath("//b[contains(text(),'Enter')]"));
        System.out.println(enterAccountInfo.isDisplayed() ? "Enter Account Information is visible" : "Enter Account Information is NOT visible");
        WebElement title = driver.findElement(By.xpath("//input[@id='id_gender2']"));
        title.click();
        Thread.sleep(3000);
        WebElement password = driver.findElement(By.xpath("//input[@id='password']"));
        password.sendKeys("123456");
        WebElement day = driver.findElement(By.xpath("//select[@id='days']"));
        day.sendKeys("12");
        WebElement month = driver.findElement(By.xpath("//select[@id='months']"));
        month.sendKeys("5");
        WebElement year = driver.findElement(By.xpath("//select[@id='years']"));
        year.sendKeys("2023");
        WebElement newsletterButton = driver.findElement(By.xpath("//input[@id='newsletter']"));
        newsletterButton.click();
        WebElement receiveOffersButton = driver.findElement(By.xpath("//input[@id='optin']"));
        receiveOffersButton.click();
        WebElement firstName = driver.findElement(By.xpath("//input[@id='first_name']"));
        firstName.sendKeys("Guli");
        WebElement lastName = driver.findElement(By.xpath("//input[@id='last_name']"));
        lastName.sendKeys("Nova");
        WebElement company = driver.findElement(By.xpath("//input[@id='company']"));
        company.sendKeys("Nova Corp.inc");
        WebElement address = driver.findElement(By.xpath("//input[@id='address1']"));
        address.sendKeys("123 Devon Street");
        WebElement country = driver.findElement(By.xpath("//select[@id='country']"));
        company.sendKeys("United States");
        WebElement state = driver.findElement(By.xpath("//input[@id='state']"));
        state.sendKeys("IL");
        WebElement city = driver.findElement(By.xpath("//input[@id='city']"));
        city.sendKeys("Chicago");
        WebElement zipcode = driver.findElement(By.xpath("//input[@id='zipcode']"));
        zipcode.sendKeys("60012");
        WebElement phoneNumber = driver.findElement(By.xpath("//input[@id='mobile_number']"));
        phoneNumber.sendKeys("123456789");
        Thread.sleep(3000);
        WebElement createAccountButton = driver.findElement(By.xpath("//button[@data-qa='create-account']"));
        Thread.sleep(3000);
        createAccountButton.click();
        WebElement accountCreated = driver.findElement(By.xpath("//b"));
        System.out.println(accountCreated.isDisplayed() ? "Account Created is Visible" : "Account Created is NOT Visible");
        WebElement continueButton = driver.findElement(By.xpath("//a[@data-qa='continue-button']"));
        Thread.sleep(3000);
        continueButton.click();
        Thread.sleep(2000);
        WebElement loggedInAs = driver.findElement(By.xpath("//i[@class='fa fa-user']"));
        Thread.sleep(2000);
        System.out.println(loggedInAs.isDisplayed() ? "Logged in as username is Visible" : "Logged in NOT Visible");
        WebElement deleteAccount = driver.findElement(By.xpath("//i[@class='fa fa-trash-o']"));
        Thread.sleep(3000);
        deleteAccount.click();
        WebElement accountDeleted = driver.findElement(By.xpath("//b"));
        System.out.println(accountDeleted.isDisplayed() ? "Account Deleted is Visible" : "Account Deleted is NOT Visible");
        driver.close();
    }
}
